const songsList1 = [

    { 曲名: "イオシス秋の爆食祭2024" },
    { 曲名: "Irregular Clock（裏）" },
    { 曲名: "オペレート・ミー（裏）" },
    { 曲名: "第六天魔王（裏）" },
    { 曲名: "for Q（裏）" },
    { 曲名: "Infinite Rebellion" },
    { 曲名: "彁（裏）" },
    { 曲名: "The Future of the 太鼓ドラム（裏）" },
    { 曲名: "神竜 ～Shinryu～（裏）" },
    { 曲名: "Central Dogma Pt.1（裏）" },
    { 曲名: "憎悪と醜悪の花束（裏）" },
    { 曲名: "第六天魔王（表）" },
    { 曲名: "ダンガンノーツ（裏）" },
    { 曲名: "Destination 2F29" },
    { 曲名: "ドンカマ2000" },
    { 曲名: "23時54分 陽の旅路へのプレリュード（裏）" },
    { 曲名: "Vixtory（裏）" },
    { 曲名: "poxei♦DOON" },
    { 曲名: "幽玄ノ乱" },
    { 曲名: "ラ・モレーナ・クモナイ（裏）" },
    { 曲名: "アンリミテッドゲームズ（裏）" },
    { 曲名: "Emma（裏）" },
    { 曲名: "!!!カオスタイム!!!" },
    { 曲名: "カオスタイム the DARK" },
    { 曲名: "疾風怒濤（裏）" },
    { 曲名: "双竜ノ乱" },
    { 曲名: "!!!チルノのパーフェクトさんすうタイム!!!" },
    { 曲名: "まださいたま2000" },
    { 曲名: "モノクロボイス（裏）" },
    { 曲名: "彁（表）" },
    { 曲名: "仮想現実のテレスコープ（裏）" },
    { 曲名: "CUT! into the FUTURE（裏）" },
    { 曲名: "Calamity Fortune（裏）" },
    { 曲名: "業 -善なる神とこの世の悪について-（裏）" },
    { 曲名: "狂瀾怒濤（裏）" },
    { 曲名: "Coquette" },
    { 曲名: "最果の魔法使い（裏）" },
    { 曲名: "スーハー2000" },
    { 曲名: "続・〆ドレー2000" },
    { 曲名: "そして勇者は眠りにつく（裏）" },
    { 曲名: "Taiko Drum Monster（裏）" },
    { 曲名: "魑魅魍魎" },
    { 曲名: "Challengers" },
    { 曲名: "≠ＭＭ" },
    { 曲名: "とける（裏）" },
    { 曲名: "初音ミクの消失‐劇場版‐（裏）" },
    { 曲名: "星屑ストラック（裏）" },
    { 曲名: "Lδchesis（裏）" },
    { 曲名: "λ7708" },
    { 曲名: "わら得る2000" },
    { 曲名: "Xa（裏）" },
    { 曲名: "氷竜～Kooryu～（裏）" },
    { 曲名: "Genesis Ray（裏）" },
    { 曲名: "たいこの2000" },
    { 曲名: "チャーリーダッシュ！" },
    { 曲名: "Nosferatu（裏）" },
    { 曲名: "Hurtling Boys" },
    { 曲名: "POLARiSNAUT" },
    { 曲名: "UFO Swingin" },
    { 曲名: "アムピト◇リーテー" },
    { 曲名: "美しく忙しきドナウ（裏）" },
    { 曲名: "ouroboros -twin stroke of the end-" },
    { 曲名: "χ談" },
    { 曲名: "カラフル" },
    { 曲名: "彼は誰時の誘惑（裏）" },
    { 曲名: "ココドコ？多分ドッカ島！（裏）" },
    { 曲名: "コネクトカラーズ" },
    { 曲名: "GORI × GORI × SafaRI（裏）" },
    { 曲名: "The Future of the 太鼓ドラム（表）" },
    { 曲名: "万戈イム－一ノ十" },
    { 曲名: "青天の黎明" },
    { 曲名: "Central Dogma Pt.2" },
    { 曲名: "Taiko Drum Monster（表）" },
    { 曲名: "DEBSTEP!" },
    { 曲名: "Dreadnought（裏）" },
    { 曲名: "Dont Stop the Game" },
    { 曲名: "HARDCOREノ心得" },
    { 曲名: "幕末維新譚" },
    { 曲名: "バチムチ マッスルキングダム" },
    { 曲名: "Hello, Worldooon!!（裏）" },
    { 曲名: "パン vs ごはん！ 大決戦！（裏）" },
    { 曲名: "Behemoth" },
    { 曲名: "まるくてはやくてすさまじいリズム" },
    { 曲名: "モノクロームユートピア" },
    { 曲名: "ラパスの虹（裏）" },
    { 曲名: "赤と白薔薇の魔女" },
    { 曲名: "あめふりのロンド（裏）" },
    { 曲名: "ON SAY GO SAY（裏）" },
    { 曲名: "カルメン組曲 一番終曲（裏）" },
    { 曲名: "森羅万象" },
    { 曲名: "デッド・オア・ダイ" },
    { 曲名: "23時54分、陽の旅路へのプレリュード" },
    { 曲名: "にゃーにゃーにゃー" },
    { 曲名: "メタナイトの逆襲メドレー（裏）" },
    { 曲名: "8OROCHI（裏）" },
    { 曲名: "哀 want U" },
    { 曲名: "或ル不和" },
    { 曲名: "VERTeX" },
    { 曲名: "ウルトラマンX（裏）" },
    { 曲名: "郢曲／暁闇" },
    { 曲名: "Agent Hustle & Dr. Hassle（表）" },
    { 曲名: "GERBERA" },
    { 曲名: "〆ドレー2000" },
    { 曲名: "重金属フューギティブ" },
    { 曲名: "Xevel" },
    { 曲名: "其方、激昂" },
    { 曲名: "SORA-VII シグナスウォール" },
	{ 曲名: "超絶技巧系少女" },
	{ 曲名: "テトラリュトモスフォビア" },
	{ 曲名: "天泣の律" },
	{ 曲名: "転生 TENSEI -喜与志が待つ強者-（裏）" },
	{ 曲名: "Toon Towns Toys Tune" },
	{ 曲名: "ナイトメア・サバイバー（裏）" },
	{ 曲名: "BATTLE NO.1" },
	{ 曲名: "Honey Heartbeat ～10 Stars Mix～（裏）" },
	{ 曲名: "Parousia" },
	{ 曲名: "パン vs ごはん！ 大決戦！（表）" },
	{ 曲名: "プチポチ" },
	{ 曲名: "FLOWER（裏）" },
	{ 曲名: "Mood Swing（裏）" },
	{ 曲名: "もぺもぺ" },
	{ 曲名: "螺旋周回軌道（裏）" },
	{ 曲名: "LECIEL GLISSANDO" },
	{ 曲名: "冷凍庫CJ ～嗚呼面太鼓ブラザーズ～" },
	{ 曲名: "ARMAGEΔDON" },
	{ 曲名: "Unwelcome School (MRM REMIX)（裏）" },
	{ 曲名: "EterNal Ring" },
	{ 曲名: "懐中庭園を持つ少女" },
	{ 曲名: "絡繰廻廊" },
	{ 曲名: "Caribbean Knight" },
	{ 曲名: "GIGALODOON（裏）" },
	{ 曲名: "鼓立あおはる学園校歌" },
	{ 曲名: "束ね糸" },
	{ 曲名: "チルノのパーフェクトさんすう教室➈周年バージョン（裏）" },
	{ 曲名: "儚姫は原初に舞う（裏）" },
	{ 曲名: "ひよこ鑑定士さん" },
	{ 曲名: "BLAZING VORTEX（裏）" },
	{ 曲名: "Players High" },
	{ 曲名: "ANiMA" },
	{ 曲名: "Altale（裏）" },
	{ 曲名: "Aleph-0" },
	{ 曲名: "UNDEAD HEART(怒りのWarriors)" },
	{ 曲名: "怒槌" },
	{ 曲名: "OK I’m blue rat" },
	{ 曲名: "KAGEKIYO（裏）" },
	{ 曲名: "CUT! into the FUTURE" },
	{ 曲名: "極圏" },
	{ 曲名: "クラポルポルスカ" },
	{ 曲名: "Got more raves?（裏）" },
	{ 曲名: "秋竜 ～Shiuryu～（裏）" },
	{ 曲名: "疾風怒濤（表）" },
	{ 曲名: "承認欲Q" },
	{ 曲名: "晨星ト鵺" },
	{ 曲名: "SUPERNOVA（裏）" },
	{ 曲名: "Stick Trick ShowTime!!" },
	{ 曲名: "月読命" },
	{ 曲名: "電脳幻夜の星言詠" },
	{ 曲名: "トイマチック☆パレード!!" },
	{ 曲名: "Doom Noiz" },
	{ 曲名: "Hello, Mr.JOKER" },
	{ 曲名: "人のお金で焼肉を食したい！（裏）" },
	{ 曲名: "FUJIN Rumble" },
	{ 曲名: "ヘイラ（裏）" },
	{ 曲名: "ヘイラ（にじさんじVer.）（裏）" },
	{ 曲名: "またさいたま2000" },
	{ 曲名: "三瀬川乱舞（裏）" },
	{ 曲名: "メカデス。（裏）" },
	{ 曲名: "めためた☆ゆにば～すっ！（裏）" },
	{ 曲名: "モノクロボイス（表）" },
	{ 曲名: "Re End of a Dream（裏）" },
	{ 曲名: "竜と黒炎の姫君（裏）" },
	{ 曲名: "練習曲Op.10-4（裏）" },
	{ 曲名: "Rotter Tarmination（裏）" },
	{ 曲名: "六本の薔薇と采の歌（裏）" },
	{ 曲名: "Whats in the box?" },
	{ 曲名: "Aragami" },
	{ 曲名: "Garakuta Doll Play（裏）" },
	{ 曲名: "カラフルボイス（裏）" },
	{ 曲名: "Calculator" },
	{ 曲名: "Kill My Fortune（裏）" },
	{ 曲名: "ゲゲゲの鬼太郎（裏）" },
	{ 曲名: "刻竜～Kokuryu～" },
	{ 曲名: "神竜 ～Shinryu～（表）" },
	{ 曲名: "Scarlet Lance" },
	{ 曲名: "星河一天" },
	{ 曲名: "憎悪と醜悪の花束（表）" },
	{ 曲名: "Destr0yer（裏）" },
	{ 曲名: "ドドドドドンだフル！（裏）" },
	{ 曲名: "はたラク2000" },
	{ 曲名: "Vixtory（表）" },
	{ 曲名: "秘ナルメジェドノ悲ナル憂鬱" },
	{ 曲名: "メタルホーク BGM1" },
	{ 曲名: "memoria ficta" },
	{ 曲名: "燎原ノ舞" },
	{ 曲名: "愛と浄罪の森" },
	{ 曲名: "アサガオ" },
	{ 曲名: "あの日出会えたキセキ" },
	{ 曲名: "Abyss of hell（裏）" },
	{ 曲名: "天照" },
	{ 曲名: "Ignis Danse" },
	{ 曲名: "Illusion Flare" },
	{ 曲名: "うちゅうひこうし冒険譚" },
	{ 曲名: "ex寅 Trap!!" },
	{ 曲名: "Evidence of evil" },
	{ 曲名: "カラ鞠の花" },
	{ 曲名: "気焔万丈神楽" },
	{ 曲名: "ギガンティックO.T.N（裏）" },
	{ 曲名: "きゅうくらりん（裏）" },
	{ 曲名: "共奏鼓祭（裏）" },
	{ 曲名: "Chronomia" },
	{ 曲名: "弧" },
	{ 曲名: "濃紅（にじさんじVer.）" },
	{ 曲名: "濃紅" },
	{ 曲名: "ゴーストマスク" },
	{ 曲名: "Goldfish City" },
	{ 曲名: "ココロボ" },
	{ 曲名: "ゴッドソング（裏）" },
	{ 曲名: "God Ray" },
	{ 曲名: "鼓舞曲「閻魔」" },
	{ 曲名: "紫煌ノ乱" },
	{ 曲名: "須佐之男" },
	{ 曲名: "Spectral Rider" },
	{ 曲名: "D's Adventure Note" },
	{ 曲名: "D絶対！SAMURAIインザレイン（裏）" },
	{ 曲名: "てんぢく2000" },
	{ 曲名: "とける（表）" },
	{ 曲名: "Doppelgangers（裏）" },
	{ 曲名: "白鳥の湖～still a duckling～（裏）" },
	{ 曲名: "ハンロック" },
	{ 曲名: "ペットショップ大戦" },
	{ 曲名: "MagiCatz" },
	{ 曲名: "六華の舞" },
	{ 曲名: "wonderful ROUTINE" },
	{ 曲名: "あなたとトゥラッタッタ♪（裏）" },
	{ 曲名: "アンリミテッドゲームズ" },
	{ 曲名: "Gloria" },
	{ 曲名: "Central Dogma Pt.1（表）" },
	{ 曲名: "弩蚊怒夏" },
	{ 曲名: "夏祭り ジッタリン・ジン（裏）" },
	{ 曲名: "Purple Rose Fusion" },
	{ 曲名: "ミュージック・リボルバー（裏）" },
	{ 曲名: "MEGALOVANIA（裏）" },
	{ 曲名: "4+1のそれぞれの未来" },
	{ 曲名: "アキバ20XX" },
	{ 曲名: "頂" },
	{ 曲名: "Aloft in the wind（裏）" },
	{ 曲名: "INSPION" },
	{ 曲名: "ウィーアー！（裏）" },
	{ 曲名: "waitin for u" },
	{ 曲名: "Angel Halo" },
	{ 曲名: "オーバード（裏）" },
	{ 曲名: "オーブの祈り" },
	{ 曲名: "GIGALODOON（表）" },
	{ 曲名: "きたさいたま2000" },
	{ 曲名: "キャラメル・ジャンキヰ" },
	{ 曲名: "Surf Zapping" },
	{ 曲名: "最終鬼畜妹フランドール・S" },
	{ 曲名: "Silent Jealousy（裏）" },
	{ 曲名: "セイクリッド ルイン（裏）" },
	{ 曲名: "零の交響曲（裏）" },
	{ 曲名: "そつおめしき2ばん" },
	{ 曲名: "十露盤2000" },
	{ 曲名: "Diving Drive" },
	{ 曲名: "ダンガンノーツ（表）" },
	{ 曲名: "天下統一録" },
	{ 曲名: "Dogbite" },
	{ 曲名: "ドドンガド～ン（裏）" },
	{ 曲名: "No Gravity" },
	{ 曲名: "ノるどん2000" },
	{ 曲名: "VICTORIA" },
	{ 曲名: "ピコピコ ルイン（裏）" },
	{ 曲名: "VIVIVIVID" },
	{ 曲名: "FREEDOM DiVE↓" },
	{ 曲名: "Venomous（裏）" },
	{ 曲名: "星屑ストラック（表）" },
	{ 曲名: "8OROCHI（表）" },
	{ 曲名: "YOAKE" },
	{ 曲名: "夜桜謝肉祭（裏）" },
	{ 曲名: "ラヴ♡スパイス♡ライクユー!!!" },
	{ 曲名: "Libera Ray" },
	{ 曲名: "詩謳兎揺蕩兎" },
	{ 曲名: "ゴーゴー・キッチン（裏）" },
	{ 曲名: "タイコタイム（裏）" },
	{ 曲名: "乱数調整のリバースシンデレラ（裏）" },
	{ 曲名: "R.I." },
	{ 曲名: "蒼の旋律（裏）" },
	{ 曲名: "朱の旋律" },
	{ 曲名: "EkiBEN2000" },
	{ 曲名: "Kamikaze Remix" },
	{ 曲名: "Calamity Fortune（表）" },
	{ 曲名: "キューティー☆デモニック☆魔人エモ!!" },
	{ 曲名: "さちさちにしてあげる♪（裏）" },
	{ 曲名: "スーパーD＆D ～完全にリードしてアイマイミー～" },
	{ 曲名: "SUPERNOVA（表）" },
	{ 曲名: "SstTAarR" },
	{ 曲名: "タイコロール" },
	{ 曲名: "タベルナ2000" },
	{ 曲名: "儚姫は原初に舞う（表）" },
	{ 曲名: "ヒバナ（裏）" },
	{ 曲名: "Blessed Bouquet Buskers" },
	{ 曲名: "よーいドン！" },
	{ 曲名: "そつおめしき" },
	{ 曲名: "Black Rose Apostle（表）" },
	{ 曲名: "Black Rose Apostle（裏）" },
	{ 曲名: "マツヨイナイトバグ（裏）" },
	{ 曲名: "X-DAY2000" },
	{ 曲名: "Clotho クロートー" },
	{ 曲名: "旋風ノ舞【天】（表）" },
	{ 曲名: "旋風ノ舞【天】（裏）" },
	{ 曲名: "チルノのパーフェクトさんすう教室（裏）" },
	{ 曲名: "ネクロファンタジア ～ Arr.Demetori" },
	{ 曲名: "拝啓ドッペルゲンガー" },
	{ 曲名: "mint tears" }
];   

const songsList2 = [
　  { 曲名: "アムピト◇リーテー" },
    { 曲名: "美しく忙しきドナウ（裏）" },
    { 曲名: "ouroboros -twin stroke of the end-" },
    { 曲名: "χ談" },
    { 曲名: "カラフル" },
    { 曲名: "彼は誰時の誘惑（裏）" },
    { 曲名: "ココドコ？多分ドッカ島！（裏）" },
    { 曲名: "コネクトカラーズ" },
    { 曲名: "GORI × GORI × SafaRI（裏）" },
    { 曲名: "The Future of the 太鼓ドラム（表）" },
    { 曲名: "万戈イム－一ノ十" },
    { 曲名: "青天の黎明" },
    { 曲名: "Central Dogma Pt.2" },
    { 曲名: "Taiko Drum Monster（表）" },
    { 曲名: "DEBSTEP!" },
    { 曲名: "Dreadnought（裏）" },
    { 曲名: "Dont Stop the Game" },
    { 曲名: "HARDCOREノ心得" },
    { 曲名: "幕末維新譚" },
    { 曲名: "バチムチ マッスルキングダム" },
    { 曲名: "Hello, Worldooon!!（裏）" },
    { 曲名: "パン vs ごはん！ 大決戦！（裏）" },
    { 曲名: "Behemoth" },
    { 曲名: "まるくてはやくてすさまじいリズム" },
    { 曲名: "モノクロームユートピア" },
    { 曲名: "ラパスの虹（裏）" },
    { 曲名: "赤と白薔薇の魔女" },
    { 曲名: "あめふりのロンド（裏）" },
    { 曲名: "ON SAY GO SAY（裏）" },
    { 曲名: "カルメン組曲 一番終曲（裏）" },
    { 曲名: "森羅万象" },
    { 曲名: "デッド・オア・ダイ" },
    { 曲名: "23時54分、陽の旅路へのプレリュード" },
    { 曲名: "にゃーにゃーにゃー" },
    { 曲名: "メタナイトの逆襲メドレー（裏）" },
    { 曲名: "8OROCHI（裏）" },
    { 曲名: "哀 want U" },
    { 曲名: "或ル不和" },
    { 曲名: "VERTeX" },
    { 曲名: "ウルトラマンX（裏）" },
    { 曲名: "郢曲／暁闇" },
    { 曲名: "Agent Hustle & Dr. Hassle（表）" },
    { 曲名: "GERBERA" },
    { 曲名: "〆ドレー2000" },
    { 曲名: "重金属フューギティブ" },
    { 曲名: "Xevel" },
    { 曲名: "其方、激昂" },
    { 曲名: "SORA-VII シグナスウォール" },
	{ 曲名: "超絶技巧系少女" },
	{ 曲名: "テトラリュトモスフォビア" },
	{ 曲名: "天泣の律" },
	{ 曲名: "転生 TENSEI -喜与志が待つ強者-（裏）" },
	{ 曲名: "Toon Towns Toys Tune" },
	{ 曲名: "ナイトメア・サバイバー（裏）" },
	{ 曲名: "BATTLE NO.1" },
	{ 曲名: "Honey Heartbeat ～10 Stars Mix～（裏）" },
	{ 曲名: "Parousia" },
	{ 曲名: "パン vs ごはん！ 大決戦！（表）" },
	{ 曲名: "プチポチ" },
	{ 曲名: "FLOWER（裏）" },
	{ 曲名: "Mood Swing（裏）" },
	{ 曲名: "もぺもぺ" },
	{ 曲名: "螺旋周回軌道（裏）" },
	{ 曲名: "LECIEL GLISSANDO" },
	{ 曲名: "冷凍庫CJ ～嗚呼面太鼓ブラザーズ～" },
	{ 曲名: "ARMAGEΔDON" },
	{ 曲名: "Unwelcome School (MRM REMIX)（裏）" },
	{ 曲名: "EterNal Ring" },
	{ 曲名: "懐中庭園を持つ少女" },
	{ 曲名: "絡繰廻廊" },
	{ 曲名: "Caribbean Knight" },
	{ 曲名: "GIGALODOON（裏）" },
	{ 曲名: "鼓立あおはる学園校歌" },
	{ 曲名: "束ね糸" },
	{ 曲名: "チルノのパーフェクトさんすう教室➈周年バージョン（裏）" },
	{ 曲名: "儚姫は原初に舞う（裏）" },
	{ 曲名: "ひよこ鑑定士さん" },
	{ 曲名: "BLAZING VORTEX（裏）" },
	{ 曲名: "Players High" },
	{ 曲名: "ANiMA" },
	{ 曲名: "Altale（裏）" },
	{ 曲名: "Aleph-0" },
	{ 曲名: "UNDEAD HEART(怒りのWarriors)" },
	{ 曲名: "怒槌" },
	{ 曲名: "OK I’m blue rat" },
	{ 曲名: "KAGEKIYO（裏）" },
	{ 曲名: "CUT! into the FUTURE" },
	{ 曲名: "極圏" },
	{ 曲名: "クラポルポルスカ" },
	{ 曲名: "Got more raves?（裏）" },
	{ 曲名: "秋竜 ～Shiuryu～（裏）" },
	{ 曲名: "疾風怒濤（表）" },
	{ 曲名: "承認欲Q" },
	{ 曲名: "晨星ト鵺" },
	{ 曲名: "SUPERNOVA（裏）" },
	{ 曲名: "Stick Trick ShowTime!!" },
	{ 曲名: "月読命" },
	{ 曲名: "電脳幻夜の星言詠" },
	{ 曲名: "トイマチック☆パレード!!" },
	{ 曲名: "Doom Noiz" },
	{ 曲名: "Hello, Mr.JOKER" },
	{ 曲名: "人のお金で焼肉を食したい！（裏）" },
	{ 曲名: "FUJIN Rumble" },
	{ 曲名: "ヘイラ（裏）" },
	{ 曲名: "ヘイラ（にじさんじVer.）（裏）" },
	{ 曲名: "またさいたま2000" },
	{ 曲名: "三瀬川乱舞（裏）" },
	{ 曲名: "メカデス。（裏）" },
	{ 曲名: "めためた☆ゆにば～すっ！（裏）" },
	{ 曲名: "モノクロボイス（表）" },
	{ 曲名: "Re End of a Dream（裏）" },
	{ 曲名: "竜と黒炎の姫君（裏）" },
	{ 曲名: "練習曲Op.10-4（裏）" },
	{ 曲名: "Rotter Tarmination（裏）" },
	{ 曲名: "六本の薔薇と采の歌（裏）" },
	{ 曲名: "Whats in the box?" },
	{ 曲名: "Aragami" },
	{ 曲名: "Garakuta Doll Play（裏）" },
	{ 曲名: "カラフルボイス（裏）" },
	{ 曲名: "Calculator" },
	{ 曲名: "Kill My Fortune（裏）" },
	{ 曲名: "ゲゲゲの鬼太郎（裏）" },
	{ 曲名: "刻竜～Kokuryu～" },
	{ 曲名: "神竜 ～Shinryu～（表）" },
	{ 曲名: "Scarlet Lance" },
	{ 曲名: "星河一天" },
	{ 曲名: "憎悪と醜悪の花束（表）" },
	{ 曲名: "Destr0yer（裏）" },
	{ 曲名: "ドドドドドンだフル！（裏）" },
	{ 曲名: "はたラク2000" },
	{ 曲名: "Vixtory（表）" },
	{ 曲名: "秘ナルメジェドノ悲ナル憂鬱" },
	{ 曲名: "メタルホーク BGM1" },
	{ 曲名: "memoria ficta" },
	{ 曲名: "燎原ノ舞" },
	{ 曲名: "愛と浄罪の森" },
	{ 曲名: "アサガオ" },
	{ 曲名: "あの日出会えたキセキ" },
	{ 曲名: "Abyss of hell（裏）" },
	{ 曲名: "天照" },
	{ 曲名: "Ignis Danse" },
	{ 曲名: "Illusion Flare" },
	{ 曲名: "うちゅうひこうし冒険譚" },
	{ 曲名: "ex寅 Trap!!" },
	{ 曲名: "Evidence of evil" },
	{ 曲名: "カラ鞠の花" },
	{ 曲名: "気焔万丈神楽" },
	{ 曲名: "ギガンティックO.T.N（裏）" },
	{ 曲名: "きゅうくらりん（裏）" },
	{ 曲名: "共奏鼓祭（裏）" },
	{ 曲名: "Chronomia" },
	{ 曲名: "弧" },
	{ 曲名: "濃紅（にじさんじVer.）" },
	{ 曲名: "濃紅" },
	{ 曲名: "ゴーストマスク" },
	{ 曲名: "Goldfish City" },
	{ 曲名: "ココロボ" },
	{ 曲名: "ゴッドソング（裏）" },
	{ 曲名: "God Ray" },
	{ 曲名: "鼓舞曲「閻魔」" },
	{ 曲名: "紫煌ノ乱" },
	{ 曲名: "須佐之男" },
	{ 曲名: "Spectral Rider" },
	{ 曲名: "D's Adventure Note" },
	{ 曲名: "D絶対！SAMURAIインザレイン（裏）" },
	{ 曲名: "てんぢく2000" },
	{ 曲名: "とける（表）" },
	{ 曲名: "Doppelgangers（裏）" },
	{ 曲名: "白鳥の湖～still a duckling～（裏）" },
	{ 曲名: "ハンロック" },
	{ 曲名: "ペットショップ大戦" },
	{ 曲名: "MagiCatz" },
	{ 曲名: "六華の舞" },
	{ 曲名: "wonderful ROUTINE" },
	{ 曲名: "あなたとトゥラッタッタ♪（裏）" },
	{ 曲名: "アンリミテッドゲームズ" },
	{ 曲名: "Gloria" },
	{ 曲名: "Central Dogma Pt.1（表）" },
	{ 曲名: "弩蚊怒夏" },
	{ 曲名: "夏祭り ジッタリン・ジン（裏）" },
	{ 曲名: "Purple Rose Fusion" },
	{ 曲名: "ミュージック・リボルバー（裏）" },
	{ 曲名: "MEGALOVANIA（裏）" },
	{ 曲名: "4+1のそれぞれの未来" },
	{ 曲名: "アキバ20XX" },
	{ 曲名: "頂" },
	{ 曲名: "Aloft in the wind（裏）" },
	{ 曲名: "INSPION" },
	{ 曲名: "ウィーアー！（裏）" },
	{ 曲名: "waitin for u" },
	{ 曲名: "Angel Halo" },
	{ 曲名: "オーバード（裏）" },
	{ 曲名: "オーブの祈り" },
	{ 曲名: "GIGALODOON（表）" },
	{ 曲名: "きたさいたま2000" },
	{ 曲名: "キャラメル・ジャンキヰ" },
	{ 曲名: "Surf Zapping" },
	{ 曲名: "最終鬼畜妹フランドール・S" },
	{ 曲名: "Silent Jealousy（裏）" },
	{ 曲名: "セイクリッド ルイン（裏）" },
	{ 曲名: "零の交響曲（裏）" },
	{ 曲名: "そつおめしき2ばん" },
	{ 曲名: "十露盤2000" },
	{ 曲名: "Diving Drive" },
	{ 曲名: "ダンガンノーツ（表）" },
	{ 曲名: "天下統一録" },
	{ 曲名: "Dogbite" },
	{ 曲名: "ドドンガド～ン（裏）" },
	{ 曲名: "No Gravity" },
	{ 曲名: "ノるどん2000" },
	{ 曲名: "VICTORIA" },
	{ 曲名: "ピコピコ ルイン（裏）" },
	{ 曲名: "VIVIVIVID" },
	{ 曲名: "FREEDOM DiVE↓" },
	{ 曲名: "Venomous（裏）" },
	{ 曲名: "星屑ストラック（表）" },
	{ 曲名: "8OROCHI（表）" },
	{ 曲名: "YOAKE" },
	{ 曲名: "夜桜謝肉祭（裏）" },
	{ 曲名: "ラヴ♡スパイス♡ライクユー!!!" },
	{ 曲名: "Libera Ray" },
	{ 曲名: "詩謳兎揺蕩兎" },
	{ 曲名: "ゴーゴー・キッチン（裏）" },
	{ 曲名: "タイコタイム（裏）" },
	{ 曲名: "乱数調整のリバースシンデレラ（裏）" },
	{ 曲名: "R.I." },
	{ 曲名: "蒼の旋律（裏）" },
	{ 曲名: "朱の旋律" },
	{ 曲名: "EkiBEN2000" },
	{ 曲名: "Kamikaze Remix" },
	{ 曲名: "Calamity Fortune（表）" },
	{ 曲名: "キューティー☆デモニック☆魔人エモ!!" },
	{ 曲名: "さちさちにしてあげる♪（裏）" },
	{ 曲名: "スーパーD＆D ～完全にリードしてアイマイミー～" },
	{ 曲名: "SUPERNOVA（表）" },
	{ 曲名: "SstTAarR" },
	{ 曲名: "タイコロール" },
	{ 曲名: "タベルナ2000" },
	{ 曲名: "儚姫は原初に舞う（表）" },
	{ 曲名: "ヒバナ（裏）" },
	{ 曲名: "Blessed Bouquet Buskers" },
	{ 曲名: "よーいドン！" },
	{ 曲名: "そつおめしき" },
	{ 曲名: "Black Rose Apostle（表）" },
	{ 曲名: "Black Rose Apostle（裏）" },
	{ 曲名: "マツヨイナイトバグ（裏）" },
	{ 曲名: "X-DAY2000" },
	{ 曲名: "Clotho クロートー" },
	{ 曲名: "旋風ノ舞【天】（表）" },
	{ 曲名: "旋風ノ舞【天】（裏）" },
	{ 曲名: "チルノのパーフェクトさんすう教室（裏）" },
	{ 曲名: "ネクロファンタジア ～ Arr.Demetori" },
	{ 曲名: "拝啓ドッペルゲンガー" },
	{ 曲名: "mint tears" }
];

const songsList3 = [
     { 曲名: "イオシス秋の爆食祭2024" },
    { 曲名: "Irregular Clock（裏）" },
    { 曲名: "オペレート・ミー（裏）" },
    { 曲名: "第六天魔王（裏）" },
    { 曲名: "for Q（裏）" },
    { 曲名: "Infinite Rebellion" },
    { 曲名: "彁（裏）" },
    { 曲名: "The Future of the 太鼓ドラム（裏）" },
    { 曲名: "神竜 ～Shinryu～（裏）" },
    { 曲名: "Central Dogma Pt.1（裏）" },
    { 曲名: "憎悪と醜悪の花束（裏）" },
    { 曲名: "第六天魔王（表）" },
    { 曲名: "ダンガンノーツ（裏）" },
    { 曲名: "Destination 2F29" },
    { 曲名: "ドンカマ2000" },
    { 曲名: "23時54分 陽の旅路へのプレリュード（裏）" },
    { 曲名: "Vixtory（裏）" },
    { 曲名: "poxei♦DOON" },
    { 曲名: "幽玄ノ乱" },
    { 曲名: "ラ・モレーナ・クモナイ（裏）" },
    { 曲名: "アンリミテッドゲームズ（裏）" },
    { 曲名: "Emma（裏）" },
    { 曲名: "!!!カオスタイム!!!" },
    { 曲名: "カオスタイム the DARK" },
    { 曲名: "疾風怒濤（裏）" },
    { 曲名: "双竜ノ乱" },
    { 曲名: "!!!チルノのパーフェクトさんすうタイム!!!" },
    { 曲名: "まださいたま2000" },
    { 曲名: "モノクロボイス（裏）" },
    { 曲名: "彁（表）" },
    { 曲名: "仮想現実のテレスコープ（裏）" },
    { 曲名: "CUT! into the FUTURE（裏）" },
    { 曲名: "Calamity Fortune（裏）" },
    { 曲名: "業 -善なる神とこの世の悪について-（裏）" },
    { 曲名: "狂瀾怒濤（裏）" },
    { 曲名: "Coquette" },
    { 曲名: "最果の魔法使い（裏）" },
    { 曲名: "スーハー2000" },
    { 曲名: "続・〆ドレー2000" },
    { 曲名: "そして勇者は眠りにつく（裏）" },
    { 曲名: "Taiko Drum Monster（裏）" },
    { 曲名: "魑魅魍魎" },
    { 曲名: "Challengers" },
    { 曲名: "≠ＭＭ" },
    { 曲名: "とける（裏）" },
    { 曲名: "初音ミクの消失‐劇場版‐（裏）" },
    { 曲名: "星屑ストラック（裏）" },
    { 曲名: "Lδchesis（裏）" },
    { 曲名: "λ7708" },
    { 曲名: "わら得る2000" },
    { 曲名: "Xa（裏）" },
    { 曲名: "氷竜～Kooryu～（裏）" },
    { 曲名: "Genesis Ray（裏）" },
    { 曲名: "たいこの2000" },
    { 曲名: "チャーリーダッシュ！" },
    { 曲名: "Nosferatu（裏）" },
    { 曲名: "Hurtling Boys" },
    { 曲名: "POLARiSNAUT" },
    { 曲名: "UFO Swingin" },
    { 曲名: "アムピト◇リーテー" },
    { 曲名: "美しく忙しきドナウ（裏）" },
    { 曲名: "ouroboros -twin stroke of the end-" },
    { 曲名: "χ談" },
    { 曲名: "カラフル" },
    { 曲名: "彼は誰時の誘惑（裏）" },
    { 曲名: "ココドコ？多分ドッカ島！（裏）" },
    { 曲名: "コネクトカラーズ" },
    { 曲名: "GORI × GORI × SafaRI（裏）" },
    { 曲名: "The Future of the 太鼓ドラム（表）" },
    { 曲名: "万戈イム－一ノ十" },
    { 曲名: "青天の黎明" },
    { 曲名: "Central Dogma Pt.2" },
    { 曲名: "Taiko Drum Monster（表）" },
    { 曲名: "DEBSTEP!" },
    { 曲名: "Dreadnought（裏）" },
    { 曲名: "Dont Stop the Game" },
    { 曲名: "HARDCOREノ心得" },
    { 曲名: "幕末維新譚" },
    { 曲名: "バチムチ マッスルキングダム" },
    { 曲名: "Hello, Worldooon!!（裏）" },
    { 曲名: "パン vs ごはん！ 大決戦！（裏）" },
    { 曲名: "Behemoth" },
    { 曲名: "まるくてはやくてすさまじいリズム" },
    { 曲名: "モノクロームユートピア" },
    { 曲名: "ラパスの虹（裏）" },
    { 曲名: "赤と白薔薇の魔女" },
    { 曲名: "あめふりのロンド（裏）" },
    { 曲名: "ON SAY GO SAY（裏）" },
    { 曲名: "カルメン組曲 一番終曲（裏）" },
    { 曲名: "森羅万象" },
    { 曲名: "デッド・オア・ダイ" },
    { 曲名: "23時54分、陽の旅路へのプレリュード" },
    { 曲名: "にゃーにゃーにゃー" },
    { 曲名: "メタナイトの逆襲メドレー（裏）" },
    { 曲名: "8OROCHI（裏）" },
    { 曲名: "哀 want U" },
    { 曲名: "或ル不和" },
    { 曲名: "VERTeX" },
    { 曲名: "ウルトラマンX（裏）" },
    { 曲名: "郢曲／暁闇" },
    { 曲名: "Agent Hustle & Dr. Hassle（表）" },
    { 曲名: "GERBERA" },
    { 曲名: "〆ドレー2000" },
    { 曲名: "重金属フューギティブ" },
    { 曲名: "Xevel" },
    { 曲名: "其方、激昂" },
    { 曲名: "SORA-VII シグナスウォール" },
	{ 曲名: "超絶技巧系少女" },
	{ 曲名: "テトラリュトモスフォビア" },
	{ 曲名: "天泣の律" },
	{ 曲名: "転生 TENSEI -喜与志が待つ強者-（裏）" },
	{ 曲名: "Toon Towns Toys Tune" },
	{ 曲名: "ナイトメア・サバイバー（裏）" },
	{ 曲名: "BATTLE NO.1" },
	{ 曲名: "Honey Heartbeat ～10 Stars Mix～（裏）" },
	{ 曲名: "Parousia" },
	{ 曲名: "パン vs ごはん！ 大決戦！（表）" },
	{ 曲名: "プチポチ" },
	{ 曲名: "FLOWER（裏）" },
	{ 曲名: "Mood Swing（裏）" },
	{ 曲名: "もぺもぺ" },
	{ 曲名: "螺旋周回軌道（裏）" },
	{ 曲名: "LECIEL GLISSANDO" },
	{ 曲名: "冷凍庫CJ ～嗚呼面太鼓ブラザーズ～" },
	{ 曲名: "ARMAGEΔDON" },
	{ 曲名: "Unwelcome School (MRM REMIX)（裏）" },
	{ 曲名: "EterNal Ring" },
	{ 曲名: "懐中庭園を持つ少女" },
	{ 曲名: "絡繰廻廊" },
	{ 曲名: "Caribbean Knight" },
	{ 曲名: "GIGALODOON（裏）" },
	{ 曲名: "鼓立あおはる学園校歌" },
	{ 曲名: "束ね糸" },
	{ 曲名: "チルノのパーフェクトさんすう教室➈周年バージョン（裏）" },
	{ 曲名: "儚姫は原初に舞う（裏）" },
	{ 曲名: "ひよこ鑑定士さん" },
	{ 曲名: "BLAZING VORTEX（裏）" },
	{ 曲名: "Players High" },
];

function getRandomSongs(songs, num) {
    const shuffled = [...songs]; // 元の配列をコピー
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1)); // ランダムなインデックス
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]; // 要素を交換
    }
    return shuffled.slice(0, num); // 最初のnum曲を返す
}

// 曲リストをクリアする関数
function clearSongLists() {
    document.getElementById('songList').innerHTML = ''; // 曲リスト1をクリア
    document.getElementById('songList2').innerHTML = ''; // 曲リスト2をクリア
    document.getElementById('songList3').innerHTML = ''; // 曲リスト3をクリア
    document.getElementById('resultTitle').textContent = ''; // 結果タイトルをクリア
}

// 1つ目のボタンのイベントリスナー
document.getElementById('randomizeBtn').addEventListener('click', () => {
    clearSongLists(); // すべての曲リストをクリア
    const selectedSongs = getRandomSongs(songsList1, 4); // 4曲を選ぶ
    const songListDiv = document.getElementById('songList');
    document.getElementById('resultTitle').textContent = "☆10全曲からの選曲結果"; // 結果のタイトルを表示

    selectedSongs.forEach(song => {
        const songItem = document.createElement('div');
        songItem.className = 'song-item';
        songItem.textContent = song.曲名; // 曲名を表示
        songListDiv.appendChild(songItem);
    });
});

// 2つ目のボタンのイベントリスナー
document.getElementById('randomizeBtn2').addEventListener('click', () => {
    clearSongLists(); // すべての曲リストをクリア
    const selectedSongs = getRandomSongs(songsList2, 4); // 4曲を選ぶ
    const songListDiv = document.getElementById('songList2');
    document.getElementById('resultTitle').textContent = "A＋以下からの選曲結果"; // 結果のタイトルを表示

    selectedSongs.forEach(song => {
        const songItem = document.createElement('div');
        songItem.className = 'song-item';
        songItem.textContent = song.曲名; // 曲名を表示
        songListDiv.appendChild(songItem);
    });
});

// 3つ目のボタンのイベントリスナー
document.getElementById('randomizeBtn3').addEventListener('click', () => {
    clearSongLists(); // すべての曲リストをクリア
    const selectedSongs = getRandomSongs(songsList3, 4); // 4曲を選ぶ
    const songListDiv = document.getElementById('songList3');
    document.getElementById('resultTitle').textContent = "双打除く個人差A以上から選曲"; // 結果のタイトルを表示

    selectedSongs.forEach(song => {
        const songItem = document.createElement('div');
        songItem.className = 'song-item';
        songItem.textContent = song.曲名; // 曲名を表示
        songListDiv.appendChild(songItem);
    });
});
